baseURL = "https://betterme.xin/" # The URL of your site.
title = "To be better me." # Title of your site
keywords = "Blog,生活,编程,分享"
theme = "zzo" # Name of Zzo theme folder in `themes/`.

defaultContentLanguage = "en" # Default language to use (if you setup multilingual support)
defaultContentLanguageInSubdir = false # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.

summaryLength = 70
buildFuture = true

copyright = "&copy;2019-{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
paginate = 10 # Number of items per page in paginated lists.
rssLimit = 100

enableGitInfo = false
googleAnalytics = ""
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


